spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      #数据库名称（可以与数据库中的库名不一致）
      names: alipay,sales
      alipay:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://118.178.56.206:3306/shard1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liran123


      sales:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://118.178.56.206:3306/shard2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liran123


    sharding:
      default-data-source-name: alipay

      # 多个table换行方式 下面对齐 |
      #      binding-tables: |toc_trade_refund_order_header,toc_trade_refund_order_detail,toc_sales_order_header,
      #                        |toc_sales_order_detail,toc_sales_deliver_header,toc_sales_deliver_detail,toc_alipay_origin,

      ## 分库
      #      default-database-strategy:
      #        standard:
      #          range-algorithm-class-name: com.test.sharding.config.sharding.DefaultDatabaseRangeShardingAlgorithm
      #          precise-algorithm-class-name: com.test.sharding.config.sharding.DefaultDatabaseShardingAlgorithm
      #          sharding-column: shop_id
      #      ## 分表字段
      #      default-table-strategy:
      #        standard:
      #          range-algorithm-class-name: com.test.sharding.config.sharding.DefaultTableRangeShardingAlgorithm
      #          precise-algorithm-class-name: com.test.sharding.config.sharding.DefaultTableShardingAlgorithm
      #          sharding-column: created
      tables:
        # 这个table名字 要注意和下面的一样
        insert_month:
          key-generator:
            column: finance_no
            type: SNOWFLAKE
          actual-data-nodes: alipay.insert_month_$->{2020..2021}0$->{1..9}, alipay.insert_month_$->{2020..2021}$->{10..12},
            sales.insert_month_$->{2020..2021}0$->{1..9}, sales.insert_month_$->{2020..2021}$->{10..12}
          table-strategy:
            standard:
              range-algorithm-class-name: com.test.sharding.config.sharding.DefaultTableRangeShardingAlgorithm
              precise-algorithm-class-name: com.test.sharding.config.sharding.DefaultTableShardingAlgorithm
              sharding-column: create_date_time
          database-strategy:
            standard:
              range-algorithm-class-name: com.test.sharding.config.sharding.DefaultDatabaseRangeShardingAlgorithm
              precise-algorithm-class-name: com.test.sharding.config.sharding.DefaultDatabaseShardingAlgorithm
              sharding-column: shop_id

## 启动参数 -Dport=8014 -Dprofiles_active=dev -Dgroup=SD  -Xms300M -Xmx300M

