server:
  port: ${port:8092}
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 5048MB
      max-request-size: 5048MB
      resolve-lazily: true
  profiles:
    active: dev

  application:
    name: sharding-test

mybatis-plus:
  mapper-locations: classpath:com/test/**/dao/**/*.xml
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    map-underscore-to-camel-case: true
logging:
  level:
    com.test.sharding: DEBUG
  file:
    name: logs/sharding-jdbc-test.log


mybatis:
  type-aliases-package: com.test.sharding.model


